kind: Service
apiVersion: v1
metadata:
  name: api
  labels:
    app: jug-api
    visualize: "true"
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9000"
    prometheus.io/path: "/prometheus"
  namespace: jug
spec:
  selector:
    app: jug-api
  ports:
  - name: http
    port: 8080
    protocol: TCP
  - name: management
    port: 9000
    protocol: TCP